version: "3.8"

services:
  backend:
    build: ./backend
    container_name: power_backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/models:/app/models:ro
    environment:
      - MODEL_NAME=lgbm

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8080
    container_name: power_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend

networks:
  default:
    name: power_load_network
